### ISSUE TITLE
Mysql, Swiftのconfigが未設定のとき，requests.exceptions.MissingSchemaとなります

### ISSUE THREAD

**Issue by ryohei-ochi** [sun-yryr/Rec-adio#21]
はじめまして、声優ラジオが好きなので、ぜひとも導入したいのですが…
サービスが起動しないので、直接run.pyを叩いてみましたが…

`# python3.7 /root/Rec-adio/run.py
Traceback (most recent call last):
  File "/root/Rec-adio/run.py", line 3, in <module>
    from lib import radiko, agqr, onsen, hibiki, functions as f
  File "/root/Rec-adio/lib/radiko.py", line 8, in <module>
    import lib.functions as f
  File "/root/Rec-adio/lib/functions.py", line 195, in <module>
    Swift = SwiftController()
  File "/root/Rec-adio/lib/functions.py", line 126, in __init__
    if not self.renewal_token():
  File "/root/Rec-adio/lib/functions.py", line 146, in renewal_token
    data=json.dumps(data))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 506, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 449, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/tokens': No schema supplied. Perhaps you meant http:///tokens?`

という感じで、radikoのセッションが取れていないような感じです。

DropBoxは容量がカツカツなので、ローカル保存したいのですが…
Pythonは不慣れなので、ソースが読めなくて申し訳ないです…

**Comment by chottokun** [comment]
はじめまして。私も導入試行錯誤中です。ド素人ですが参考になればと思いcommentします。

お使いになってない場合は、configからswiftとmysqlを外して（記述ごと削除）してはどうでしょう。swiftを設定せずいたとき同じエラー吐いてましたよ。

作者様、便利なプログラムありがとうございます。

**Comment by ryohei-ochi** [comment]
ありがとうございます！
ご指摘のようにswiftとmysqlの設定をまるっと消したら、動いているような感じです！

しばらく様子を見てみますが、
番組情報をmysqlに格納して、phpから視聴管理したいなぁ～
っと、思っているので、また時間を見つけてソースを確認してみます。

録音が確認できましたら、Closeしますね。

**Comment by chottokun** [comment]
他には、FFmpeg でエラー出たくらいで、当方ではうまく動いています。
クラウドストレージへのuploadは、rclone に任せてもいいかなぁと思っています。issueから外れるのでこのあたりで・・・。

まずは録音うまくいきますように・・・です。

**Comment by sun-yryr** [comment]
使っていただきありがとうございます。
現状chottokunさんの解決方法が正しいです。

エラー処理がアホだったので次のリリースで直します……

**Comment by ryohei-ochi** [comment]
ゆるゆる様
ありがとうございます！
コンソールで挙動を確認してますが、無事に録音が出来たみたいです。
ひとまず、このIssueはCloseしておきますね！
今後の開発にも期待してます！
![IMG_-df80v1](https://user-images.githubusercontent.com/49377186/72765430-b66dcc80-3c2f-11ea-9809-b49d13d3f590.jpg)
![IMG_-nhtffu](https://user-images.githubusercontent.com/49377186/72765435-c08fcb00-3c2f-11ea-8daf-86a659b45952.jpg)

**Comment by sun-yryr** [comment]
ryohei-ochiさんありがとうございます！
直したら閉じるので（同じバク踏んでる人もいるかも知れない）reopenしますね

（うーんradikoがバグっている……）

**Comment by ryohei-ochi** [comment]
失礼しました(^_^;)
よろしくお願いします！

**Comment by sun-yryr** [comment]
https://github.com/sun-yryr/Rec-adio/commit/c3843ea970659751b4ac18857712e685134ef176
